<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 canti.glb --transform -t
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Cube001: THREE.SkinnedMesh
      Cube001_1: THREE.SkinnedMesh
      Cube001_2: THREE.SkinnedMesh
      Cube: THREE.SkinnedMesh
      Cube_1: THREE.SkinnedMesh
      Cube_2: THREE.SkinnedMesh
      Cube_3: THREE.SkinnedMesh
      Cube_4: THREE.SkinnedMesh
      Cube_5: THREE.SkinnedMesh
      Cube_6: THREE.SkinnedMesh
      Cube_7: THREE.SkinnedMesh
      Cube_8: THREE.SkinnedMesh
      Cube_9: THREE.SkinnedMesh
      main: THREE.Bone
    }
    materials: {
      jacket: THREE.MeshBasicMaterial
      black: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/assets/models/canti-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group position={[0, 0.03, -0.16]}>
      <T is={gltf.nodes.main} />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube001.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube001.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube001_1.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube001_1.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube001_2.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube001_2.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_1.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_1.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_2.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_2.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_3.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_3.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_4.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_4.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_5.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_5.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_6.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_6.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_7.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_7.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_8.geometry}
        material={gltf.materials.jacket}
        skeleton={gltf.nodes.Cube_8.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Cube_9.geometry}
        material={gltf.materials.black}
        skeleton={gltf.nodes.Cube_9.skeleton}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
